prefix : "&7[&6CompassRadar&7]"
customrecipe : true
format : "&e{target} - {range} block(s)"
radar:
  name: "&bPlayer Radar"
  lore:
    - "&eThis radar will be pointed to"
    - "&enearest player in your world."
gui: true

#Custom recipe enables you to create a radar by putting compass in a crafting grid
#
#Available format variables:
#{name} - Name of the player
#{target} - Target of radar
#{range} - Range between player to target in blocks
#
#You can provide as many lines you want for item lore.
#
#To disable the GUI feature, set gui to false.
